import std/os
import std/strformat
import std/terminal

import term

const version = "0.1.0"

proc displayHelp*(args: seq[string] = @[]) =
  let t = termInit()
  let option = if args.len >= 1: args[0] else: ""
  let appFilename = getAppFilename().lastPathPart()
  
  case option
  of "a", "i", "add", "install":
    t.write(2, fgCyan, "a, add <arg>", "\n")
    t.write(2, fgCyan, "i, install <arg>", "\n\n")
    t.write(2, fgWhite, "Installs an addon from a url or project name. Supported sites are github, gitlab, tukui, wowinterface, curseforge, wago.io, zremax, and legacy-wow.\n\n")
    t.write(2, fgGreen, "EXAMPLES:", "\n")
    t.write(3, fgBlue, "Github:", "\n")
    t.write(4, fgWhite, &"{appFilename} install https://github.com/Stanzilla/AdvancedInterfaceOptions", "\n")
    t.write(4, fgWhite, &"{appFilename} install github:Stanzilla/AdvancedInterfaceOptions", "\n")
    t.write(4, &"{appFilename} install https://github.com/Tercioo/Plater-Nameplates/tree/master", "\n")
    t.write(4, &"{appFilename} install github:Tercioo/Plater-Nameplates@master", "\n")
    t.write(6, fgGreen, "⬑", fgYellow, "Including the branch will install and track the latest commit to that branch instead of releases.", "\n")
    t.write(3, fgBlue, "Gitlab:", "\n")
    t.write(4, fgWhite, &"{appFilename} install https://gitlab.com/woblight/actionmirroringframe", "\n")
    t.write(4, fgWhite, &"{appFilename} install gitlab:woblight/actionmirroringframe", "\n")
    t.write(3, fgBlue, "WoW Interface:", "\n")
    t.write(4, fgWhite, &"{appFilename} install https://www.wowinterface.com/downloads/info24608-HekiliPriorityHelper.html", "\n")
    t.write(4, &"{appFilename} install wowint:24608", "\n")
    t.write(3, fgBlue, "Tukui:", "\n")
    t.write(4, fgWhite, &"{appFilename} install https://www.tukui.org/elvui", "\n")
    t.write(4, &"{appFilename} install tukui:elvui", "\n")
    t.write(3, fgBlue, "Curseforge:", "\n")
    t.write(4, fgWhite, &"{appFilename} install https://www.curseforge.com/api/v1/mods/334372/files/4956577/download", "\n")
    t.write(4, &"{appFilename} install curse:334372", "\n")
    t.write(6, fgGreen, "⬑", fgYellow, "To get this url, go the addon page and click download, then click the download button, then copy the link for 'try again.'", "\n")
    t.write(6, fgYellow, " For curseforge, using the Project ID is easier. Locate the ID on the right side of the addon page.", "\n")
    t.write(3, fgBlue, "Wago.io:", "\n")
    t.write(4, fgWhite, &"{appFilename} install https://addons.wago.io/addons/rarescanner", "\n")
    t.write(4, fgWhite, &"{appFilename} install wago:rarescanner", "\n")
    t.write(3, fgBlue, "Zremax:", "\n")
    t.write(4, fgWhite, &"{appFilename} install https://zremax.com/wow/addons/gearscorelite", "\n")
    t.write(4, &"{appFilename} install zremax:gearscorelite", "\n")
    t.write(3, fgBlue, "Legacy-wow:", "\n")
    t.write(4, fgWhite, &"{appFilename} install https://legacy-wow.com/cata-addons/recount/", "\n")
    t.write(4, &"{appFilename} install legacy-wow:cata-addons/recount", "\n")
    t.write(6, fgGreen, "⬑", fgYellow, "Legacy-wow addons do not update. Use another source if the addon is being actively updated.", "\n")
    
  of "c", "config":
    t.write(2, fgCyan, "c, config [options]", "\n\n")
    t.write(2, fgWhite, "Sets various configuration options. If no options are provided, displays the current configuration.\n\n")
    t.write(2, fgGreen, "OPTIONS:", "\n")
    t.write(4, fgCyan, "backup [path|on|off]\n")
    t.write(6, fgWhite, "Replace path with the location of the backup directory. The default is located inside the WoW Interface directory.\n")
    t.write(6, "On or off enables or disables backups respectively.\n")
    t.write(4, fgCyan, "github <token>\n")
    t.write(6, fgWhite, "Sets a github personal access token. This may be required to fix 403 forbidden responses for too may requests.\n")
    t.write(4, fgCyan, "path [wow directory]\n")
    t.write(6, fgWhite, "Sets the WoW directory if you want to run hearthsync from a different directory.\n")

  of "l", "list":
    t.write(2, fgCyan, "l, list [options]", "\n\n")
    t.write(2, fgWhite, "Lists installed addons. The default order is alphabetical.\n\n")
    t.write(2, fgGreen, "OPTIONS:", "\n")
    t.write(4, fgCyan, "[t|time]\n")
    t.write(6, fgWhite, "Sort by most recent install or update time.\n\n")
    t.write(4, fgCyan, "[all]\n")
    t.write(6, fgWhite, "Show full information for each addon.\n\n")

  else:
    t.write(2, fgGreen, "Hearthsync", fgYellow, " ", version, fgWhite, " by Michael Green\n\n", resetStyle)
    t.write(2, true, fgCyan, "a, add <addon>")
    t.write(30, fgWhite, "Install an addon.", "\n")
    t.write(2, true, fgCyan, "c, config [options]")
    t.write(30, fgWhite, "Configuration options.", "\n")
    t.write(2, true, fgCyan, "h, help [options]")
    t.write(30, fgWhite, "Displays this message. If an option is provided, displays help for that option.", "\n")
    t.write(2, true, fgCyan, "i, install <addon>")
    t.write(30, fgWhite, "Alias for add", "\n")
    t.write(2, true, fgCyan, "l, list [options]")
    t.write(30, fgWhite, "List installed addons sorted by name.", "\n")
    t.write(2, true, fgCyan, "n, name <id> <name>")
    t.write(30, fgWhite, "Set your own <name> for addon with <id>. Must use quotes around <name> if it contains spaces.\n")
    t.write(30, fgWhite, "Leave <name> blank to go back to the default name.\n")
    t.write(5, true, fgCyan, "pin <id1> <id2> ...")
    t.write(30, fgWhite, "Pin addon to the current version. Addon will not be updated until unpinned.", "\n")
    t.write(2, true, fgCyan, "r, remove <id1> <id2> ...")
    t.write(30, fgWhite, "Remove installed addons by id number", "\n")
    t.write(5, true, fgCyan, "reinstall")
    t.write(30, fgWhite, "Force a reinstall of all addons. Can be used to restore from an existing hearthsync.addons file.", "\n")
    t.write(5, true, fgCyan, "restore <id1> <id2> ...")
    t.write(30, fgWhite, "Restore addons to the version prior to last update if backups were enabled when installed.", "\n")
    t.write(5, true, fgCyan, "revert")
    t.write(30, fgWhite, "Restore all addons to the version prior to last update if backups were enabled when installed.", "\n")
    t.write(5, true, fgCyan, "unpin <id1> <id2> ...")
    t.write(30, fgWhite, "Unpin addon to restore updates.", "\n")
    t.write(2, true, fgCyan, "u, update")
    t.write(30, fgWhite, "Update all installed addons. The default if no arguments are given.", "\n")
  quit()